export const DEFAULT_IMPACT_FACTORS = {
  // 500+
  'CA – A Cancer Journal for Clinicians': 508.7,

  // 90–100
  'The New England Journal of Medicine': 96.2,
  'The Lancet': 98.4,

  // 80–89
  'Nature Medicine': 82.9,

  // 70–79
  'Nature Reviews Cancer': 72.0,
  'Nature Reviews Gastroenterology & Hepatology': 73.0,

  // 60–69
  'JAMA': 63.1,
  'Nature Reviews Immunology': 67.8,
  'Nature Reviews Clinical Oncology': 66.0,

  // 50–59
  'Annals of Oncology': 51.8,
  'Nature Reviews Disease Primers': 50.5,
  'Nature Reviews Microbiology': 57.3,
  'Nature Reviews Neurology': 57.3,
  'Lancet Infectious Diseases': 56.3,

  // 40–49
  'Nature Reviews Neuroscience': 46.0,
  'Journal of Clinical Oncology': 45.3,
  'Nature Reviews Cardiology': 41.7,
  'Nature Reviews Nephrology': 42.1,
  'BMJ': 39.0,
  'Annals of Internal Medicine': 39.0,
  'European Heart Journal': 39.3,
  'Nature Reviews Rheumatology': 39.0,
  'Intensive Care Medicine': 38.9,
  'Circulation': 37.8,

  // 30–39
  'Gastroenterology': 33.0,
  'Gut': 31.8,
  'Clinical Microbiology Reviews': 30.5,

  // 20–29
  'JAMA Psychiatry': 25.8,
  'Blood': 25.5,
  'American Journal of Respiratory and Critical Care Medicine': 24.7,
  'Journal of the American College of Cardiology': 24.0,
  'Clinical Infectious Diseases': 20.4,

  // 10–19
  'Radiology': 19.7,
  'British Journal of Sports Medicine': 18.4,
  'Diabetes Care': 16.2,
  'Nature Reviews Urology': 15.0,
  'JAMA Dermatology': 15.0,
  'Annual Review of Medicine': 14.7,
  'Brain': 14.5,
  'Molecular Neurodegeneration': 14.4,
  'Journal of Experimental Medicine': 14.3,
  'Journal of Clinical Investigation': 13.3,
  'The Journal of Clinical Investigation': 13.3,
  'Canadian Medical Association Journal': 13.2,
  'Annals of Surgery': 13.0,
  'American Journal of Gastroenterology': 13.0,
  'Journal of Cachexia, Sarcopenia and Muscle': 12.1,
  'JAMA Internal Medicine': 12.0,
  'Neurology': 11.2,
  'Diabetes': 11.2,
  'British Journal of Dermatology': 11.1,
  'Anaesthesia': 10.7,
  'Stroke': 10.7,
  'Thorax': 10.5,
  'PLoS Medicine': 10.5,
  'Arteriosclerosis, Thrombosis, and Vascular Biology': 10.4,

  // 9
  'Chest': 9.6,
  'Critical Care Medicine': 9.4,
  'Alimentary Pharmacology & Therapeutics': 9.0,
  'Anesthesiology': 9.1,
  'British Journal of Anaesthesia': 9.1,
  'American Journal of Transplantation': 8.9,
  'Hypertension': 8.9,
  'American Journal of Obstetrics and Gynecology': 9.8,

  // 8
  'Critical Care': 8.8,
  'British Journal of Cancer': 8.8,
  'British Journal of Surgery': 8.6,
  'Cardiovascular Diabetology': 8.5,
  'American Journal of Public Health': 8.2,
  'Bulletin of the World Health Organization': 8.4,
  'JAMA Ophthalmology': 8.1,
  'Pediatrics': 8.0,
  'Obstetrics and Gynecology': 8.0,
  'American Journal of Sports Medicine': 7.8,

  // 7
  'Annals of Intensive Care': 7.5,
  'Journal of Investigative Dermatology': 7.6,
  'Reviews in Endocrine and Metabolic Disorders': 7.6,
  'Pain': 7.4,
  'Allergy, Asthma & Immunology Research': 7.2,
  'EuroIntervention': 7.2,
  'Clinical Pharmacology & Therapeutics': 7.0,
  'European Radiology': 7.0,
  'BMC Medicine': 7.0,

  // 6
  'Acta Psychiatrica Scandinavica': 6.8,
  'Human Reproduction': 6.8,
  'Resuscitation': 6.5,
  'Journal of Clinical Endocrinology and Metabolism': 5.9,
  'Neural Regeneration Research': 6.1,
  'Annals of Emergency Medicine': 6.2,

  // 5
  'Journal of Immunology': 5.7,
  'Bone Marrow Transplantation': 5.7,
  'Journal of Medical Genetics': 5.7,
  'Heart': 5.7,
  'BJUI': 5.4,
  'Medicine & Science in Sports & Exercise': 5.4,
  'Journal of Bone and Joint Surgery': 5.3,
  'Preventive Medicine': 5.3,
  'Investigative Ophthalmology & Visual Science': 5.0,
  'The Medical Journal of Australia': 5.0,
  'Osteoporosis International': 5.0,
  'Journal of the American College of Surgeons': 5.0,
  'Regional Anesthesia and Pain Medicine': 5.1,
  'Seminars in Thrombosis and Hemostasis': 5.2,

  // 4
  'Journal of Pediatrics': 4.9,
  'Clinical Gastroenterology and Hepatology': 11.4,
  'AIDS': 4.7,
  'British Journal of Ophthalmology': 4.6,
  'PLoS Neglected Tropical Diseases': 4.6,
  'Expert Review of Respiratory Medicine': 4.5,
  'BMC Cancer': 4.5,
  'Molecular Medicine': 4.5,
  'Anesthesia and Analgesia': 4.5,
  'The Journal of Pain': 4.3,
  'Pediatric Research': 4.2,
  'Surgery for Obesity and Related Diseases': 4.2,
  'Endocrinology': 4.2,
  'QJM: An International Journal of Medicine': 4.1,
  'Archives of Disease in Childhood': 4.4,
  'Breast Cancer Research and Treatment': 4.4,
  'Pharmacotherapy': 4.0,

  // 3
  'Frontiers in Medicine': 3.9,
  'European Journal of Anaesthesiology': 3.9,
  'Spine': 3.7,
  'Advances in Therapy': 3.8,
  'Evolution, Medicine, and Public Health': 3.8,
  'International Journal of Surgery': 3.8,
  'Journal of Intensive Care': 3.8,
  'Cardiovascular Drugs and Therapy': 3.6,
  'European Journal of Pain': 3.6,
  'Academic Emergency Medicine': 3.6,
  'Clinical Journal of Sport Medicine': 3.6,
  'Current Pain and Headache Reports': 3.5,
  'The Annals of Pharmacotherapy': 3.5,
  'Surgical Endoscopy': 3.5,
  'Clinical Lung Cancer': 3.5,
  'Journal of Critical Care': 3.4,
  'Cancer Medicine': 3.4,
  'Journal of Clinical Anesthesia': 3.1,
  'Chinese Medical Journal': 3.1,
  'Postgraduate Medicine': 3.1,
  'Clinical Breast Cancer': 3.1,
  'Journal of Pediatric Gastroenterology and Nutrition': 3.0,
  'Journal of Pain Research': 3.0,
  'American Journal of Medical Genetics': 3.0,
  'Neuropsychiatric Disease and Treatment': 3.0,
  'Current Medical Research and Opinion': 3.0,
  'COPD: Journal of Chronic Obstructive Pulmonary Disease': 3.0,
  'Perioperative Medicine': 2.9,
  'Statistics in Medicine': 2.9,
  'Clinical Toxicology': 2.9,

  // 2
  'Acta Anaesthesiologica Scandinavica': 2.8,
  'Emergency Medicine Journal': 2.8,
  'American Journal of the Medical Sciences': 2.8,
  'Journal of the Royal Society of Medicine': 2.8,
  'Transactions of the Royal Society of Tropical Medicine and Hygiene': 2.8,
  'Internal Medicine Journal': 2.8,
  'American Journal of Emergency Medicine': 2.7,
  'American Journal of Tropical Medicine and Hygiene': 2.7,
  'Paediatric Anaesthesia': 2.6,
  'Current Opinion in Anesthesiology': 2.6,
  'Annals of Human Genetics': 2.5,
  'Clinical Ophthalmology': 2.5,
  'Korean Journal of Anesthesiology': 2.5,
  'Prehospital Emergency Care': 2.5,
  'Scandinavian Journal of Surgery': 2.2,
  'Annals of the Royal College of Surgeons of England': 2.1,
  'Minerva Cardiology and Angiology': 2.1,
  'Indian Journal of Medical Research': 2.1,
  'Acta Radiologica': 2.1,
  'Scandinavian Journal of Public Health': 2.0,
  'Neurorehabilitation': 2.0,
  'Canadian Respiratory Journal': 2.0,
  'Paediatrics & Child Health': 2.0,
  'Scandinavian Journal of Infectious Diseases': 2.0,

  // Under 2
  'Anaesthesia and Intensive Care': 1.8,
  'Seminars in Cardiothoracic and Vascular Anesthesia': 1.8,
  'Israel Medical Association Journal': 1.5,
  'Indian Journal of Anaesthesia': 1.5,
  'Canadian Journal of Infectious Diseases & Medical Microbiology': 1.5,
  'Neurology India': 1.3,
  'Asian Cardiovascular and Thoracic Annals': 1.2,
  'Annals of Cardiac Anaesthesia': 1.2,
  'National Medical Journal of India': 1.2,
  'Journal of Infection in Developing Countries': 1.1,
  'Le Praticien en Anesthésie Réanimation': 0.5,
};

export const JOURNAL_QUARTILES = {
  // Q1
  'The New England Journal of Medicine': 'Q1',
  'The Lancet': 'Q1',
  'JAMA': 'Q1',
  'BMJ': 'Q1',
  'Nature Medicine': 'Q1',
  'Annals of Internal Medicine': 'Q1',
  'Lancet Respiratory Medicine': 'Q1',
  'Lancet Infectious Diseases': 'Q1',
  'Nature Reviews Cancer': 'Q1',
  'Nature Reviews Cardiology': 'Q1',
  'Nature Reviews Clinical Oncology': 'Q1',
  'Nature Reviews Gastroenterology & Hepatology': 'Q1',
  'Nature Reviews Immunology': 'Q1',
  'Nature Reviews Microbiology': 'Q1',
  'Nature Reviews Nephrology': 'Q1',
  'Nature Reviews Neurology': 'Q1',
  'Nature Reviews Neuroscience': 'Q1',
  'Nature Reviews Rheumatology': 'Q1',
  'Nature Reviews Urology': 'Q1',
  'Nature Reviews Disease Primers': 'Q1',
  'CA – A Cancer Journal for Clinicians': 'Q1',
  'Intensive Care Medicine': 'Q1',
  'Critical Care Medicine': 'Q1',
  'Critical Care': 'Q1',
  'American Journal of Respiratory and Critical Care Medicine': 'Q1',
  'Anaesthesia': 'Q1',
  'Anesthesiology': 'Q1',
  'British Journal of Anaesthesia': 'Q1',
  'Regional Anesthesia and Pain Medicine': 'Q1',
  'Circulation': 'Q1',
  'European Heart Journal': 'Q1',
  'Journal of the American College of Cardiology': 'Q1',
  'Gastroenterology': 'Q1',
  'Gut': 'Q1',
  'Journal of Clinical Oncology': 'Q1',
  'Annals of Oncology': 'Q1',
  'Blood': 'Q1',
  'Brain': 'Q1',
  'Neurology': 'Q1',
  'JAMA Psychiatry': 'Q1',
  'JAMA Internal Medicine': 'Q1',
  'JAMA Dermatology': 'Q1',
  'JAMA Ophthalmology': 'Q1',
  'JAMA Pediatrics': 'Q1',
  'JAMA Surgery': 'Q1',
  'Annals of Surgery': 'Q1',
  'British Journal of Surgery': 'Q1',
  'Diabetes Care': 'Q1',
  'Diabetes': 'Q1',
  'Hypertension': 'Q1',
  'Stroke': 'Q1',
  'Radiology': 'Q1',
  'PLoS Medicine': 'Q1',
  'BMC Medicine': 'Q1',
  'Chest': 'Q1',
  'Resuscitation': 'Q1',
  'Pain': 'Q1',
  'American Journal of Transplantation': 'Q1',
  'European Urology': 'Q1',
  'Clinical Infectious Diseases': 'Q1',
  'Clinical Microbiology Reviews': 'Q1',
  'Journal of Clinical Investigation': 'Q1',
  'The Journal of Clinical Investigation': 'Q1',
  'Journal of Experimental Medicine': 'Q1',
  'American Journal of Obstetrics and Gynecology': 'Q1',
  'Human Reproduction': 'Q1',
  'Pediatrics': 'Q1',
  'Archives of Disease in Childhood': 'Q1',
  'British Journal of Dermatology': 'Q1',
  'Journal of Investigative Dermatology': 'Q1',
  'Arteriosclerosis, Thrombosis, and Vascular Biology': 'Q1',
  'Heart': 'Q1',
  'Annals of Emergency Medicine': 'Q1',
  'American Journal of Public Health': 'Q1',
  'Alimentary Pharmacology & Therapeutics': 'Q1',
  'Clinical Gastroenterology and Hepatology': 'Q1',
  'Annals of Intensive Care': 'Q1',
  'Journal of Cachexia, Sarcopenia and Muscle': 'Q1',
  'Molecular Neurodegeneration': 'Q1',
  'Movement Disorders': 'Q1',
  'Surgery for Obesity and Related Diseases': 'Q1',
  'Thorax': 'Q1',
  'American Journal of Sports Medicine': 'Q1',
  'British Journal of Sports Medicine': 'Q1',

  // Q2
  'Anesthesia and Analgesia': 'Q2',
  'Acta Anaesthesiologica Scandinavica': 'Q2',
  'European Journal of Anaesthesiology': 'Q2',
  'Journal of Clinical Anesthesia': 'Q2',
  'Current Opinion in Anesthesiology': 'Q2',
  'Paediatric Anaesthesia': 'Q2',
  'Critical Care and Resuscitation': 'Q2',
  'Emergency Medicine Journal': 'Q2',
  'Academic Emergency Medicine': 'Q2',
  'Journal of Critical Care': 'Q2',
  'Journal of Intensive Care': 'Q2',
  'European Radiology': 'Q2',
  'American Journal of Roentgenology': 'Q2',
  'Acta Radiologica': 'Q2',
  'Journal of the American College of Surgeons': 'Q2',
  'Surgical Endoscopy': 'Q2',
  'Annals of the Royal College of Surgeons of England': 'Q2',
  'International Journal of Surgery': 'Q2',
  'Journal of Bone and Joint Surgery': 'Q2',
  'Osteoporosis International': 'Q2',
  'Spine': 'Q2',
  'Journal of Medical Genetics': 'Q2',
  'Clinical Pharmacology & Therapeutics': 'Q2',
  'Pharmacotherapy': 'Q2',
  'Journal of Clinical Endocrinology and Metabolism': 'Q2',
  'Endocrinology': 'Q2',
  'Obstetrics and Gynecology': 'Q2',
  'Journal of Pediatrics': 'Q2',
  'Pediatric Research': 'Q2',
  'American Journal of Emergency Medicine': 'Q2',
  'Prehospital Emergency Care': 'Q2',
  'Canadian Medical Association Journal': 'Q2',
  'Mayo Clinic Proceedings': 'Q2',
  'Journal of Internal Medicine': 'Q2',
  'QJM: An International Journal of Medicine': 'Q2',
  'Clinical Science': 'Q2',
  'Cardiovascular Diabetology': 'Q2',
  'EuroIntervention': 'Q2',
  'Journal of Hypertension': 'Q2',
  'American Journal of Gastroenterology': 'Q2',
  'Bone Marrow Transplantation': 'Q2',
  'Seminars in Thrombosis and Hemostasis': 'Q2',
  'Journal of Immunology': 'Q2',
  'Investigative Ophthalmology & Visual Science': 'Q2',
  'British Journal of Ophthalmology': 'Q2',
  'Neural Regeneration Research': 'Q2',
  'Neuropsychiatric Disease and Treatment': 'Q2',
  'Acta Psychiatrica Scandinavica': 'Q2',
  'Medicine & Science in Sports & Exercise': 'Q2',
  'Clinical Journal of Sport Medicine': 'Q2',
  'BJUI': 'Q2',
  'Allergy, Asthma & Immunology Research': 'Q2',
  'PLoS Neglected Tropical Diseases': 'Q2',
  'Bulletin of the World Health Organization': 'Q2',
  'Preventive Medicine': 'Q2',

  // Q3
  'Anaesthesia and Intensive Care': 'Q3',
  'Korean Journal of Anesthesiology': 'Q3',
  'Indian Journal of Anaesthesia': 'Q3',
  'Annals of Cardiac Anaesthesia': 'Q3',
  'Seminars in Cardiothoracic and Vascular Anesthesia': 'Q3',
  'Le Praticien en Anesthésie Réanimation': 'Q3',
  'Langenbeck\'s Archives of Surgery': 'Q3',
  'Scandinavian Journal of Surgery': 'Q3',
  'Turkish Journal of Surgery': 'Q3',
  'Asian Cardiovascular and Thoracic Annals': 'Q3',
  'Minerva Cardiology and Angiology': 'Q3',
  'Journal of Geriatric Cardiology': 'Q3',
  'Current Pain and Headache Reports': 'Q3',
  'The Journal of Pain': 'Q3',
  'European Journal of Pain': 'Q3',
  'Journal of Pain Research': 'Q3',
  'Clinical Ophthalmology': 'Q3',
  'Neurology India': 'Q3',
  'Neurorehabilitation': 'Q3',
  'Journal of Occupational and Environmental Medicine': 'Q3',
  'Scandinavian Journal of Public Health': 'Q3',
  'Scandinavian Journal of Infectious Diseases': 'Q3',
  'Canadian Respiratory Journal': 'Q3',
  'Canadian Journal of Gastroenterology & Hepatology': 'Q3',
  'Internal Medicine Journal': 'Q3',
  'American Journal of the Medical Sciences': 'Q3',
  'Postgraduate Medicine': 'Q3',
  'Chinese Medical Journal': 'Q3',
  'Indian Journal of Medical Research': 'Q3',
  'Israel Medical Association Journal': 'Q3',
  'National Medical Journal of India': 'Q3',
  'The Medical Journal of Australia': 'Q3',
  'Statistics in Medicine': 'Q3',
  'Evolution, Medicine, and Public Health': 'Q3',
  'Transactions of the Royal Society of Tropical Medicine and Hygiene': 'Q3',
  'American Journal of Tropical Medicine and Hygiene': 'Q3',
  'Journal of Infection in Developing Countries': 'Q3',
  'Annals of Human Genetics': 'Q3',
  'American Journal of Medical Genetics': 'Q3',

  // Q4
  'Journal of the Royal Society of Medicine': 'Q4',
  'Journal of the Royal College of Physicians of Edinburgh': 'Q4',
  'Pakistan Journal of Pharmaceutical Sciences': 'Q4',
  'Calicut Medical Journal': 'Q4',
  'Myanmar Medical Journal': 'Q4',
  'Harefuah': 'Q4',
  'Orvosi Hetilap': 'Q4',
};