import { PAPER_FIELDS } from './constants';
import { getAllPapers, putPaper, pubmedIdFromUrl } from './db';
import { fetchFullDetails, parseDoi, extractDoi } from './pubmedApi';
import { resolveLookup } from './lookupApi';
import { buildVancouverReference, decodeHtmlEntities } from './format';
import { fetchAISummary } from './aiApi';
import { isAiEnabled } from './storage';

// The metadata fields Optimise knows how to fix from PubMed/CrossRef.
// `reference` is rebuilt whenever it's active, because the citation format
// itself changed; the rest are only filled when blank or repaired when
// demonstrably broken.
export const OPTIMISABLE_FIELDS = ['title', 'reference', 'url', 'year', 'abstract'];

// Basic identity hygiene — always corrected, not part of the field picker.
// Unlike reference/abstract/AI content, these are fixes to data that is
// simply wrong (a malformed year, HTML entities in a title), not enrichment
// someone might reasonably want to skip.
export const ALWAYS_FIELDS = ['title', 'url', 'year'];

// Generated by the Anthropic API (fetchAISummary), one call per paper,
// covering all four together. Unlike the PubMed-derived fields, this costs
// real money and needs the user's own key — so these are opt-in and never
// touch a field that already has a value, only ever fill a blank one.
export const AI_FIELDS = ['subject', 'oneLineSummary', 'fullSummary', 'tags'];

// What the field picker shows, in display order.
export const SELECTABLE_FIELDS = [
  { field: 'reference', label: 'Reference', kind: 'metadata' },
  { field: 'abstract', label: 'Abstract', kind: 'metadata' },
  { field: 'subject', label: 'Subject area', kind: 'ai' },
  { field: 'oneLineSummary', label: 'One-sentence summary', kind: 'ai' },
  { field: 'fullSummary', label: 'Full summary', kind: 'ai' },
  { field: 'tags', label: 'Tags', kind: 'ai' },
];

// Reference and abstract were the original scope and cost nothing; the AI
// fields are opt-in because they cost real API usage.
export const DEFAULT_SELECTED_FIELDS = new Set(['reference', 'abstract']);

const REBUILT_ALWAYS = new Set(['reference']);

// A reference the old journal-only format produced when no metadata could be
// fetched: punctuation and nothing else, e.g. ";:" or "Anaesthesia 2020;:".
const EMPTY_REFERENCE = /^[\s;:().,-]*$/;
const TRAILING_EMPTY_LOCATOR = /[;:]\s*[;:]?\s*$/;
const HTML_ENTITY = /&(?:#\d+|#x[0-9a-f]+|amp|lt|gt|quot|deg|plusmn|times|le|ge);/i;

export function isBlank(value) {
  if (Array.isArray(value)) return value.length === 0;
  return value === undefined || value === null || String(value).trim() === '';
}

// "Broken" has to be something we can point at, not merely something we would
// have written differently — anything the user may have corrected by hand must
// survive the scan untouched.
export function fieldProblem(paper, field) {
  const value = paper[field];
  if (isBlank(value)) return 'missing';
  const text = String(value);
  switch (field) {
    case 'reference':
      if (EMPTY_REFERENCE.test(text)) return 'empty';
      if (TRAILING_EMPTY_LOCATOR.test(text)) return 'truncated';
      return null;
    case 'title':
      return HTML_ENTITY.test(text) ? 'entities' : null;
    case 'year':
      return /^\d{4}$/.test(text.trim()) ? null : 'malformed';
    case 'url':
      return /^https?:\/\//i.test(text.trim()) ? null : 'malformed';
    default:
      return null;
  }
}

// The text most likely to resolve to the right record, best identifier first.
function lookupKey(paper) {
  const pmid = pubmedIdFromUrl(paper.url);
  if (pmid) return { kind: 'pmid', value: pmid };
  const doi = parseDoi(paper.url) || extractDoi(paper.url) || extractDoi(paper.reference);
  if (doi) return { kind: 'doi', value: doi };
  if (!isBlank(paper.title)) return { kind: 'title', value: decodeHtmlEntities(paper.title).trim() };
  if (!isBlank(paper.reference)) return { kind: 'reference', value: String(paper.reference).trim() };
  return null;
}

// Resolves one paper to an authoritative record. A stored PubMed ID is treated
// as certain — it names the record outright. Anything reached by matching text
// carries the cascade's own confidence, and only its best tier is trusted
// without asking, because a wrong match rewrites a paper into a different one.
async function resolvePaper(paper) {
  const key = lookupKey(paper);
  if (!key) return { status: 'unresolvable' };

  if (key.kind === 'pmid') {
    const details = await fetchFullDetails(key.value);
    if (!details || (!details.journal && !details.pubdate)) return { status: 'unresolvable' };
    return {
      status: 'resolved',
      confidence: 'certain',
      pubmedId: key.value,
      trial: { title: paper.title, pubmedId: key.value },
      details,
    };
  }

  const resolved = await resolveLookup(key.value);
  if (!resolved?.trial) return { status: 'unresolvable' };

  const trial = resolved.trial;
  const pubmedId = trial.pubmedId || null;
  const details = pubmedId
    ? await fetchFullDetails(pubmedId)
    : trial.crossrefDetails || {};

  return {
    status: 'resolved',
    // Only a DOI names a record outright; everything else was matched on text.
    confidence: key.kind === 'doi' && resolved.confidence === 'high' ? 'certain' : (resolved.confidence || 'low'),
    pubmedId,
    trial: { ...trial, title: trial.title || paper.title },
    details,
  };
}

// What the record would become for the PubMed-derived fields. Blank proposals
// are dropped: replacing a value with nothing is never an improvement.
// `activeFields` is which of OPTIMISABLE_FIELDS this run is allowed to touch —
// ALWAYS_FIELDS plus whichever of reference/abstract the user selected.
function proposeChanges(paper, resolution, activeFields) {
  const { trial, details, pubmedId } = resolution;
  const proposed = {
    title: decodeHtmlEntities(trial.title || paper.title || '').trim(),
    reference: buildVancouverReference(trial, details || {}),
    url: pubmedId ? `https://pubmed.ncbi.nlm.nih.gov/${pubmedId}/` : (trial.url || paper.url || ''),
    year: details?.pubdate ? String(details.pubdate).split(' ')[0] : (paper.year || ''),
    abstract: details?.abstract || paper.abstract || '',
  };

  const changes = [];
  for (const field of activeFields) {
    if (!(field in proposed)) continue;
    const next = proposed[field];
    if (isBlank(next)) continue;
    const current = paper[field] ?? '';
    if (String(current).trim() === String(next).trim()) continue;

    const problem = fieldProblem(paper, field);
    // Everything except the reference is only touched when it is missing or
    // demonstrably broken — a value that merely differs is left as the user
    // has it.
    if (!REBUILT_ALWAYS.has(field) && !problem) continue;

    changes.push({ field, from: current, to: next, reason: problem || 'reformatted' });
  }
  return changes;
}

// Generates whichever selected AI fields are blank on this paper, from
// whatever title/journal/pubdate/abstract context is available — either a
// confirmed PubMed/CrossRef match, or (when there was no match) the paper's
// own stored fields. Never regenerates a field that already has a value: an
// existing summary may have been hand-edited, and the whole point of "fields
// added if missing" is that it only ever fills blanks.
async function proposeAiChanges(paper, source, selectedFields) {
  const wanted = AI_FIELDS.filter(f => selectedFields.has(f) && isBlank(paper[f]));
  if (wanted.length === 0 || !isAiEnabled()) return { changes: [], aiError: null };

  try {
    const summary = await fetchAISummary(
      { title: source.title, journal: source.journal, pubdate: source.pubdate },
      source.abstract
    );
    const changes = [];
    for (const field of wanted) {
      const next = summary[field];
      if (isBlank(next)) continue;
      changes.push({ field, from: paper[field], to: next, reason: 'missing' });
    }
    return { changes, aiError: null };
  } catch (e) {
    return { changes: [], aiError: e.message };
  }
}

// Scans the library and returns what it would change, without writing
// anything. `fields` is the set of optional fields to include (reference,
// abstract, and/or the four AI fields) — title/url/year are always checked.
// `onProgress({ done, total, title })` is called as each paper is examined.
export async function planOptimisation({ onProgress, shouldStop, fields } = {}) {
  const selectedFields = fields instanceof Set ? fields : new Set(fields || DEFAULT_SELECTED_FIELDS);
  const activeMetadataFields = OPTIMISABLE_FIELDS.filter(f => ALWAYS_FIELDS.includes(f) || selectedFields.has(f));
  const wantsAi = AI_FIELDS.some(f => selectedFields.has(f));

  const papers = await getAllPapers();
  const plan = { total: papers.length, entries: [], unresolved: [], unchanged: 0, failed: [], aiFailed: 0 };

  for (let i = 0; i < papers.length; i++) {
    if (shouldStop?.()) {
      plan.stopped = true;
      break;
    }
    const paper = papers[i];
    onProgress?.({ done: i, total: papers.length, title: paper.title });

    let resolution;
    try {
      resolution = await resolvePaper(paper);
    } catch (e) {
      plan.failed.push({ paper, message: e.message });
      continue;
    }

    if (resolution.status === 'resolved') {
      const { trial, details } = resolution;
      let changes = proposeChanges(paper, resolution, activeMetadataFields);

      const { changes: aiChanges, aiError } = await proposeAiChanges(
        paper,
        {
          title: trial.title || paper.title,
          journal: details?.journal || '',
          pubdate: details?.pubdate || paper.year,
          abstract: details?.abstract || paper.abstract,
        },
        selectedFields
      );
      if (aiError) plan.aiFailed++;
      changes = changes.concat(aiChanges);

      if (changes.length === 0) plan.unchanged++;
      else plan.entries.push({ paper, changes, confidence: resolution.confidence });
      continue;
    }

    // No PubMed/CrossRef match. The content fields can't be trusted without a
    // source, but AI enrichment can still run against what the paper already
    // has, if the user asked for it and there's at least a title to work from.
    if (wantsAi && !isBlank(paper.title)) {
      const { changes: aiChanges, aiError } = await proposeAiChanges(
        paper,
        { title: paper.title, journal: '', pubdate: paper.year, abstract: paper.abstract },
        selectedFields
      );
      if (aiError) plan.aiFailed++;
      if (aiChanges.length > 0) {
        plan.entries.push({ paper, changes: aiChanges, confidence: 'ai-only' });
        continue;
      }
    }
    plan.unresolved.push(paper);
  }

  onProgress?.({ done: papers.length, total: papers.length, title: '' });
  return plan;
}

// Writes the accepted entries. Every write goes through putPaper, so sync
// bookkeeping and per-field edit times are stamped exactly as a manual edit
// would be.
export async function applyOptimisation(entries) {
  let applied = 0;
  for (const entry of entries) {
    const updated = { ...entry.paper };
    for (const change of entry.changes) {
      if (PAPER_FIELDS.includes(change.field)) updated[change.field] = change.to;
    }
    await putPaper(updated);
    applied++;
  }
  return applied;
}
